name: flutter_iframe_webview
description: A Flutter plugin that provides a WebView widget on web.
version: 0.2.2+1
homepage:

environment:
  sdk: '>=2.19.2 <3.0.0'

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      web:
        pluginClass: WebWebViewPlatform
        fileName: webview_flutter_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  webview_flutter_platform_interface: ^2.0.0
  flutter_jsbridge_sdk: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
